# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solar_tracker.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(782, 695)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.gen = QtGui.QWidget()
        self.gen.setObjectName(_fromUtf8("gen"))
        self.gridLayout_23 = QtGui.QGridLayout(self.gen)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.gen_prvflt_graphicsView = QtGui.QGraphicsView(self.gen)
        self.gen_prvflt_graphicsView.setObjectName(_fromUtf8("gen_prvflt_graphicsView"))
        self.gridLayout_23.addWidget(self.gen_prvflt_graphicsView, 0, 0, 1, 1)
        self.gen_prvorg_graphicsView = QtGui.QGraphicsView(self.gen)
        self.gen_prvorg_graphicsView.setObjectName(_fromUtf8("gen_prvorg_graphicsView"))
        self.gridLayout_23.addWidget(self.gen_prvorg_graphicsView, 0, 1, 1, 1)
        self.gen_impro_groupBox = QtGui.QGroupBox(self.gen)
        self.gen_impro_groupBox.setObjectName(_fromUtf8("gen_impro_groupBox"))
        self.formLayout = QtGui.QFormLayout(self.gen_impro_groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.gen_impro_imsrc_label = QtGui.QLabel(self.gen_impro_groupBox)
        self.gen_impro_imsrc_label.setObjectName(_fromUtf8("gen_impro_imsrc_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.gen_impro_imsrc_label)
        self.gen_impro_imsrc_comboBox = QtGui.QComboBox(self.gen_impro_groupBox)
        self.gen_impro_imsrc_comboBox.setObjectName(_fromUtf8("gen_impro_imsrc_comboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.gen_impro_imsrc_comboBox)
        self.gen_impro_reso_label = QtGui.QLabel(self.gen_impro_groupBox)
        self.gen_impro_reso_label.setObjectName(_fromUtf8("gen_impro_reso_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.gen_impro_reso_label)
        self.gen_impro_reso_comboBox = QtGui.QComboBox(self.gen_impro_groupBox)
        self.gen_impro_reso_comboBox.setObjectName(_fromUtf8("gen_impro_reso_comboBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.gen_impro_reso_comboBox)
        self.gen_impro_opker_label = QtGui.QLabel(self.gen_impro_groupBox)
        self.gen_impro_opker_label.setObjectName(_fromUtf8("gen_impro_opker_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.gen_impro_opker_label)
        self.gen_impro_blrker_label = QtGui.QLabel(self.gen_impro_groupBox)
        self.gen_impro_blrker_label.setObjectName(_fromUtf8("gen_impro_blrker_label"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.gen_impro_blrker_label)
        self.gen_impro_opker_spinBox = QtGui.QSpinBox(self.gen_impro_groupBox)
        self.gen_impro_opker_spinBox.setMinimum(1)
        self.gen_impro_opker_spinBox.setObjectName(_fromUtf8("gen_impro_opker_spinBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.gen_impro_opker_spinBox)
        self.gen_impro_blrker_spinBox = QtGui.QSpinBox(self.gen_impro_groupBox)
        self.gen_impro_blrker_spinBox.setMinimum(1)
        self.gen_impro_blrker_spinBox.setSingleStep(2)
        self.gen_impro_blrker_spinBox.setObjectName(_fromUtf8("gen_impro_blrker_spinBox"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.gen_impro_blrker_spinBox)
        self.gridLayout_23.addWidget(self.gen_impro_groupBox, 1, 0, 1, 1)
        self.gen_man_btn_groupBox = QtGui.QGroupBox(self.gen)
        self.gen_man_btn_groupBox.setObjectName(_fromUtf8("gen_man_btn_groupBox"))
        self.gridLayout_21 = QtGui.QGridLayout(self.gen_man_btn_groupBox)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.gen_man_btn_up_pushButton = QtGui.QPushButton(self.gen_man_btn_groupBox)
        self.gen_man_btn_up_pushButton.setObjectName(_fromUtf8("gen_man_btn_up_pushButton"))
        self.gridLayout_21.addWidget(self.gen_man_btn_up_pushButton, 2, 1, 1, 1)
        self.gen_man_man_radioButton = QtGui.QRadioButton(self.gen_man_btn_groupBox)
        self.gen_man_man_radioButton.setObjectName(_fromUtf8("gen_man_man_radioButton"))
        self.gridLayout_21.addWidget(self.gen_man_man_radioButton, 1, 0, 1, 2)
        self.gen_man_btn_lft_pushButton = QtGui.QPushButton(self.gen_man_btn_groupBox)
        self.gen_man_btn_lft_pushButton.setObjectName(_fromUtf8("gen_man_btn_lft_pushButton"))
        self.gridLayout_21.addWidget(self.gen_man_btn_lft_pushButton, 2, 0, 3, 1)
        self.gen_man_btn_dwn_pushButton = QtGui.QPushButton(self.gen_man_btn_groupBox)
        self.gen_man_btn_dwn_pushButton.setObjectName(_fromUtf8("gen_man_btn_dwn_pushButton"))
        self.gridLayout_21.addWidget(self.gen_man_btn_dwn_pushButton, 4, 1, 1, 1)
        self.gen_man_btn_rt_pushButton = QtGui.QPushButton(self.gen_man_btn_groupBox)
        self.gen_man_btn_rt_pushButton.setObjectName(_fromUtf8("gen_man_btn_rt_pushButton"))
        self.gridLayout_21.addWidget(self.gen_man_btn_rt_pushButton, 3, 2, 1, 1)
        self.gen_man_auto_radioButton = QtGui.QRadioButton(self.gen_man_btn_groupBox)
        self.gen_man_auto_radioButton.setChecked(True)
        self.gen_man_auto_radioButton.setObjectName(_fromUtf8("gen_man_auto_radioButton"))
        self.gridLayout_21.addWidget(self.gen_man_auto_radioButton, 0, 0, 1, 2)
        self.gen_man_btn_rst_pushButton = QtGui.QPushButton(self.gen_man_btn_groupBox)
        self.gen_man_btn_rst_pushButton.setObjectName(_fromUtf8("gen_man_btn_rst_pushButton"))
        self.gridLayout_21.addWidget(self.gen_man_btn_rst_pushButton, 3, 1, 1, 1)
        self.gridLayout_23.addWidget(self.gen_man_btn_groupBox, 1, 1, 1, 1)
        self.gen_daily_groupBox = QtGui.QGroupBox(self.gen)
        self.gen_daily_groupBox.setObjectName(_fromUtf8("gen_daily_groupBox"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.gen_daily_groupBox)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.gen_daily_strt_groupBox = QtGui.QGroupBox(self.gen_daily_groupBox)
        self.gen_daily_strt_groupBox.setFlat(True)
        self.gen_daily_strt_groupBox.setObjectName(_fromUtf8("gen_daily_strt_groupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.gen_daily_strt_groupBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gen_daily_strt_timeEdit = QtGui.QTimeEdit(self.gen_daily_strt_groupBox)
        self.gen_daily_strt_timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.gen_daily_strt_timeEdit.setObjectName(_fromUtf8("gen_daily_strt_timeEdit"))
        self.verticalLayout_9.addWidget(self.gen_daily_strt_timeEdit)
        self.horizontalLayout_9.addWidget(self.gen_daily_strt_groupBox)
        self.gen_daily_stp_groupBox = QtGui.QGroupBox(self.gen_daily_groupBox)
        self.gen_daily_stp_groupBox.setFlat(True)
        self.gen_daily_stp_groupBox.setObjectName(_fromUtf8("gen_daily_stp_groupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.gen_daily_stp_groupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gen_daily_stp_timeEdit = QtGui.QTimeEdit(self.gen_daily_stp_groupBox)
        self.gen_daily_stp_timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.gen_daily_stp_timeEdit.setObjectName(_fromUtf8("gen_daily_stp_timeEdit"))
        self.verticalLayout_10.addWidget(self.gen_daily_stp_timeEdit)
        self.horizontalLayout_9.addWidget(self.gen_daily_stp_groupBox)
        self.gen_daily_stp_rts_checkBox = QtGui.QCheckBox(self.gen_daily_groupBox)
        self.gen_daily_stp_rts_checkBox.setMaximumSize(QtCore.QSize(111, 16777215))
        self.gen_daily_stp_rts_checkBox.setObjectName(_fromUtf8("gen_daily_stp_rts_checkBox"))
        self.horizontalLayout_9.addWidget(self.gen_daily_stp_rts_checkBox)
        self.gridLayout_23.addWidget(self.gen_daily_groupBox, 2, 0, 1, 2)
        self.tabWidget.addTab(self.gen, _fromUtf8(""))
        self.trkr = QtGui.QWidget()
        self.trkr.setObjectName(_fromUtf8("trkr"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.trkr)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.trkr_src_groupBox = QtGui.QGroupBox(self.trkr)
        self.trkr_src_groupBox.setMaximumSize(QtCore.QSize(16777215, 61))
        self.trkr_src_groupBox.setFlat(False)
        self.trkr_src_groupBox.setObjectName(_fromUtf8("trkr_src_groupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.trkr_src_groupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.trkr_src_usdef_radioButton = QtGui.QRadioButton(self.trkr_src_groupBox)
        self.trkr_src_usdef_radioButton.setChecked(True)
        self.trkr_src_usdef_radioButton.setObjectName(_fromUtf8("trkr_src_usdef_radioButton"))
        self.gridLayout_10.addWidget(self.trkr_src_usdef_radioButton, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.trkr_src_autofl_radioButton_2 = QtGui.QRadioButton(self.trkr_src_groupBox)
        self.trkr_src_autofl_radioButton_2.setObjectName(_fromUtf8("trkr_src_autofl_radioButton_2"))
        self.gridLayout_10.addWidget(self.trkr_src_autofl_radioButton_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.trkr_src_groupBox)
        self.trkr_loc_groupBox = QtGui.QGroupBox(self.trkr)
        self.trkr_loc_groupBox.setObjectName(_fromUtf8("trkr_loc_groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.trkr_loc_groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.trkr_loc_lat_groupBox = QtGui.QGroupBox(self.trkr_loc_groupBox)
        self.trkr_loc_lat_groupBox.setFlat(True)
        self.trkr_loc_lat_groupBox.setObjectName(_fromUtf8("trkr_loc_lat_groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.trkr_loc_lat_groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.trkr_loc_lat_deg_label = QtGui.QLabel(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lat_deg_label.setObjectName(_fromUtf8("trkr_loc_lat_deg_label"))
        self.gridLayout_6.addWidget(self.trkr_loc_lat_deg_label, 0, 0, 1, 1)
        self.trkr_loc_lat_min_label = QtGui.QLabel(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lat_min_label.setObjectName(_fromUtf8("trkr_loc_lat_min_label"))
        self.gridLayout_6.addWidget(self.trkr_loc_lat_min_label, 0, 1, 1, 1)
        self.trkr_loc_lat_sec_label = QtGui.QLabel(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lat_sec_label.setObjectName(_fromUtf8("trkr_loc_lat_sec_label"))
        self.gridLayout_6.addWidget(self.trkr_loc_lat_sec_label, 0, 2, 1, 1)
        self.trkr_loc_lat_deg_lineEdit = QtGui.QLineEdit(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lat_deg_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_lat_deg_lineEdit.setObjectName(_fromUtf8("trkr_loc_lat_deg_lineEdit"))
        self.gridLayout_6.addWidget(self.trkr_loc_lat_deg_lineEdit, 1, 0, 1, 1)
        self.trkr_loc_lat_min_lineEdit = QtGui.QLineEdit(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lat_min_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_lat_min_lineEdit.setObjectName(_fromUtf8("trkr_loc_lat_min_lineEdit"))
        self.gridLayout_6.addWidget(self.trkr_loc_lat_min_lineEdit, 1, 1, 1, 1)
        self.trkr_loc_lat_sec_lineEdit = QtGui.QLineEdit(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lat_sec_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_lat_sec_lineEdit.setObjectName(_fromUtf8("trkr_loc_lat_sec_lineEdit"))
        self.gridLayout_6.addWidget(self.trkr_loc_lat_sec_lineEdit, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.trkr_loc_lat_groupBox)
        self.trkr_loc_lon_groupBox = QtGui.QGroupBox(self.trkr_loc_groupBox)
        self.trkr_loc_lon_groupBox.setFlat(True)
        self.trkr_loc_lon_groupBox.setObjectName(_fromUtf8("trkr_loc_lon_groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.trkr_loc_lon_groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.trkr_loc_lon_deg_label = QtGui.QLabel(self.trkr_loc_lon_groupBox)
        self.trkr_loc_lon_deg_label.setObjectName(_fromUtf8("trkr_loc_lon_deg_label"))
        self.gridLayout_7.addWidget(self.trkr_loc_lon_deg_label, 0, 0, 1, 1)
        self.trkr_loc_lon_min_label = QtGui.QLabel(self.trkr_loc_lon_groupBox)
        self.trkr_loc_lon_min_label.setObjectName(_fromUtf8("trkr_loc_lon_min_label"))
        self.gridLayout_7.addWidget(self.trkr_loc_lon_min_label, 0, 1, 1, 1)
        self.trkr_loc_lon_sec_label = QtGui.QLabel(self.trkr_loc_lon_groupBox)
        self.trkr_loc_lon_sec_label.setObjectName(_fromUtf8("trkr_loc_lon_sec_label"))
        self.gridLayout_7.addWidget(self.trkr_loc_lon_sec_label, 0, 2, 1, 1)
        self.trkr_loc_lon_deg_lineEdit = QtGui.QLineEdit(self.trkr_loc_lon_groupBox)
        self.trkr_loc_lon_deg_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_lon_deg_lineEdit.setObjectName(_fromUtf8("trkr_loc_lon_deg_lineEdit"))
        self.gridLayout_7.addWidget(self.trkr_loc_lon_deg_lineEdit, 1, 0, 1, 1)
        self.trkr_loc_lon_min_lineEdit = QtGui.QLineEdit(self.trkr_loc_lon_groupBox)
        self.trkr_loc_lon_min_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_lon_min_lineEdit.setObjectName(_fromUtf8("trkr_loc_lon_min_lineEdit"))
        self.gridLayout_7.addWidget(self.trkr_loc_lon_min_lineEdit, 1, 1, 1, 1)
        self.trkr_loc_lon_sec_lineEdit = QtGui.QLineEdit(self.trkr_loc_lon_groupBox)
        self.trkr_loc_lon_sec_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_lon_sec_lineEdit.setObjectName(_fromUtf8("trkr_loc_lon_sec_lineEdit"))
        self.gridLayout_7.addWidget(self.trkr_loc_lon_sec_lineEdit, 1, 2, 1, 1)
        self.trkr_src_groupBox.raise_()
        self.trkr_loc_lon_deg_lineEdit.raise_()
        self.trkr_loc_lon_min_lineEdit.raise_()
        self.trkr_loc_lon_sec_lineEdit.raise_()
        self.trkr_loc_lon_deg_label.raise_()
        self.trkr_loc_lon_min_label.raise_()
        self.trkr_loc_lon_sec_label.raise_()
        self.verticalLayout_6.addWidget(self.trkr_loc_lon_groupBox)
        self.trkr_loc_alt_groupBox = QtGui.QGroupBox(self.trkr_loc_groupBox)
        self.trkr_loc_alt_groupBox.setFlat(True)
        self.trkr_loc_alt_groupBox.setObjectName(_fromUtf8("trkr_loc_alt_groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.trkr_loc_alt_groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.trkr_loc_alt_lineEdit = QtGui.QLineEdit(self.trkr_loc_alt_groupBox)
        self.trkr_loc_alt_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_alt_lineEdit.setObjectName(_fromUtf8("trkr_loc_alt_lineEdit"))
        self.gridLayout_8.addWidget(self.trkr_loc_alt_lineEdit, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.trkr_loc_alt_groupBox)
        self.trkr_loc_td_groupBox = QtGui.QGroupBox(self.trkr_loc_groupBox)
        self.trkr_loc_td_groupBox.setFlat(True)
        self.trkr_loc_td_groupBox.setObjectName(_fromUtf8("trkr_loc_td_groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.trkr_loc_td_groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.trkr_loc_td_time_label = QtGui.QLabel(self.trkr_loc_td_groupBox)
        self.trkr_loc_td_time_label.setObjectName(_fromUtf8("trkr_loc_td_time_label"))
        self.gridLayout_9.addWidget(self.trkr_loc_td_time_label, 0, 0, 1, 1)
        self.trkr_loc_td_date_label = QtGui.QLabel(self.trkr_loc_td_groupBox)
        self.trkr_loc_td_date_label.setObjectName(_fromUtf8("trkr_loc_td_date_label"))
        self.gridLayout_9.addWidget(self.trkr_loc_td_date_label, 0, 1, 1, 1)
        self.trkr_loc_td_time_timeEdit = QtGui.QTimeEdit(self.trkr_loc_td_groupBox)
        self.trkr_loc_td_time_timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_td_time_timeEdit.setObjectName(_fromUtf8("trkr_loc_td_time_timeEdit"))
        self.gridLayout_9.addWidget(self.trkr_loc_td_time_timeEdit, 1, 0, 1, 1)
        self.trkr_loc_td_date_dateEdit = QtGui.QDateEdit(self.trkr_loc_td_groupBox)
        self.trkr_loc_td_date_dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_loc_td_date_dateEdit.setObjectName(_fromUtf8("trkr_loc_td_date_dateEdit"))
        self.gridLayout_9.addWidget(self.trkr_loc_td_date_dateEdit, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.trkr_loc_td_groupBox)
        self.trkr_loc_lat_groupBox.raise_()
        self.trkr_loc_lon_groupBox.raise_()
        self.trkr_loc_td_groupBox.raise_()
        self.trkr_loc_alt_groupBox.raise_()
        self.verticalLayout_5.addWidget(self.trkr_loc_groupBox)
        self.trkr_typ_groupBox = QtGui.QGroupBox(self.trkr)
        self.trkr_typ_groupBox.setMaximumSize(QtCore.QSize(16777215, 161))
        self.trkr_typ_groupBox.setObjectName(_fromUtf8("trkr_typ_groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.trkr_typ_groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.trkr_typ_col_radioButton = QtGui.QRadioButton(self.trkr_typ_groupBox)
        self.trkr_typ_col_radioButton.setObjectName(_fromUtf8("trkr_typ_col_radioButton"))
        self.gridLayout_5.addWidget(self.trkr_typ_col_radioButton, 0, 0, 1, 1)
        self.trkr_typ_cpfh_radioButtongroupBox = QtGui.QGroupBox(self.trkr_typ_groupBox)
        self.trkr_typ_cpfh_radioButtongroupBox.setObjectName(_fromUtf8("trkr_typ_cpfh_radioButtongroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.trkr_typ_cpfh_radioButtongroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.trkr_typ_cpfh_az_groupBox = QtGui.QGroupBox(self.trkr_typ_cpfh_radioButtongroupBox)
        self.trkr_typ_cpfh_az_groupBox.setFlat(True)
        self.trkr_typ_cpfh_az_groupBox.setObjectName(_fromUtf8("trkr_typ_cpfh_az_groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.trkr_typ_cpfh_az_groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.trkr_typ_cpfh_az_lineEdit = QtGui.QLineEdit(self.trkr_typ_cpfh_az_groupBox)
        self.trkr_typ_cpfh_az_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_typ_cpfh_az_lineEdit.setObjectName(_fromUtf8("trkr_typ_cpfh_az_lineEdit"))
        self.gridLayout_4.addWidget(self.trkr_typ_cpfh_az_lineEdit, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.trkr_typ_cpfh_az_groupBox)
        self.trkr_typ_cpfh_el_groupBox = QtGui.QGroupBox(self.trkr_typ_cpfh_radioButtongroupBox)
        self.trkr_typ_cpfh_el_groupBox.setFlat(True)
        self.trkr_typ_cpfh_el_groupBox.setObjectName(_fromUtf8("trkr_typ_cpfh_el_groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.trkr_typ_cpfh_el_groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.trkr_typ_cpfh_el_lineEdit = QtGui.QLineEdit(self.trkr_typ_cpfh_el_groupBox)
        self.trkr_typ_cpfh_el_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.trkr_typ_cpfh_el_lineEdit.setObjectName(_fromUtf8("trkr_typ_cpfh_el_lineEdit"))
        self.gridLayout_3.addWidget(self.trkr_typ_cpfh_el_lineEdit, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.trkr_typ_cpfh_el_groupBox)
        self.gridLayout_5.addWidget(self.trkr_typ_cpfh_radioButtongroupBox, 0, 1, 2, 1)
        self.trkr_typ_heli_radioButton = QtGui.QRadioButton(self.trkr_typ_groupBox)
        self.trkr_typ_heli_radioButton.setChecked(True)
        self.trkr_typ_heli_radioButton.setObjectName(_fromUtf8("trkr_typ_heli_radioButton"))
        self.gridLayout_5.addWidget(self.trkr_typ_heli_radioButton, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.trkr_typ_groupBox)
        self.tabWidget.addTab(self.trkr, _fromUtf8(""))
        self.ctrl = QtGui.QWidget()
        self.ctrl.setObjectName(_fromUtf8("ctrl"))
        self.gridLayout_12 = QtGui.QGridLayout(self.ctrl)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.ctrl_timeb_groupBox = QtGui.QGroupBox(self.ctrl)
        self.ctrl_timeb_groupBox.setCheckable(True)
        self.ctrl_timeb_groupBox.setObjectName(_fromUtf8("ctrl_timeb_groupBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.ctrl_timeb_groupBox)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.ctrl_timeb_az_groupBox = QtGui.QGroupBox(self.ctrl_timeb_groupBox)
        self.ctrl_timeb_az_groupBox.setObjectName(_fromUtf8("ctrl_timeb_az_groupBox"))
        self.gridLayout_14 = QtGui.QGridLayout(self.ctrl_timeb_az_groupBox)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.ctrl_timeb_az_kp_label = QtGui.QLabel(self.ctrl_timeb_az_groupBox)
        self.ctrl_timeb_az_kp_label.setObjectName(_fromUtf8("ctrl_timeb_az_kp_label"))
        self.gridLayout_14.addWidget(self.ctrl_timeb_az_kp_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_timeb_az_kp_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_timeb_az_groupBox)
        self.ctrl_timeb_az_kp_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_timeb_az_kp_doubleSpinBox.setDecimals(4)
        self.ctrl_timeb_az_kp_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_timeb_az_kp_doubleSpinBox.setObjectName(_fromUtf8("ctrl_timeb_az_kp_doubleSpinBox"))
        self.gridLayout_14.addWidget(self.ctrl_timeb_az_kp_doubleSpinBox, 0, 1, 1, 1)
        self.ctrl_timeb_az_ki_label = QtGui.QLabel(self.ctrl_timeb_az_groupBox)
        self.ctrl_timeb_az_ki_label.setObjectName(_fromUtf8("ctrl_timeb_az_ki_label"))
        self.gridLayout_14.addWidget(self.ctrl_timeb_az_ki_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_timeb_az_ki_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_timeb_az_groupBox)
        self.ctrl_timeb_az_ki_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_timeb_az_ki_doubleSpinBox.setDecimals(4)
        self.ctrl_timeb_az_ki_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_timeb_az_ki_doubleSpinBox.setObjectName(_fromUtf8("ctrl_timeb_az_ki_doubleSpinBox"))
        self.gridLayout_14.addWidget(self.ctrl_timeb_az_ki_doubleSpinBox, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.ctrl_timeb_az_groupBox)
        self.ctrl_timeb_el_groupBox = QtGui.QGroupBox(self.ctrl_timeb_groupBox)
        self.ctrl_timeb_el_groupBox.setObjectName(_fromUtf8("ctrl_timeb_el_groupBox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.ctrl_timeb_el_groupBox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.ctrl_timeb_el_kp_label = QtGui.QLabel(self.ctrl_timeb_el_groupBox)
        self.ctrl_timeb_el_kp_label.setObjectName(_fromUtf8("ctrl_timeb_el_kp_label"))
        self.gridLayout_13.addWidget(self.ctrl_timeb_el_kp_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_timeb_el_kp_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_timeb_el_groupBox)
        self.ctrl_timeb_el_kp_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_timeb_el_kp_doubleSpinBox.setDecimals(4)
        self.ctrl_timeb_el_kp_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_timeb_el_kp_doubleSpinBox.setObjectName(_fromUtf8("ctrl_timeb_el_kp_doubleSpinBox"))
        self.gridLayout_13.addWidget(self.ctrl_timeb_el_kp_doubleSpinBox, 0, 1, 1, 1)
        self.ctrl_timeb_el_ki_label = QtGui.QLabel(self.ctrl_timeb_el_groupBox)
        self.ctrl_timeb_el_ki_label.setObjectName(_fromUtf8("ctrl_timeb_el_ki_label"))
        self.gridLayout_13.addWidget(self.ctrl_timeb_el_ki_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_timeb_el_ki_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_timeb_el_groupBox)
        self.ctrl_timeb_el_ki_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_timeb_el_ki_doubleSpinBox.setDecimals(4)
        self.ctrl_timeb_el_ki_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_timeb_el_ki_doubleSpinBox.setObjectName(_fromUtf8("ctrl_timeb_el_ki_doubleSpinBox"))
        self.gridLayout_13.addWidget(self.ctrl_timeb_el_ki_doubleSpinBox, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.ctrl_timeb_el_groupBox)
        self.gridLayout_12.addWidget(self.ctrl_timeb_groupBox, 0, 0, 1, 1)
        self.ctrl_imageb_groupBox = QtGui.QGroupBox(self.ctrl)
        self.ctrl_imageb_groupBox.setCheckable(True)
        self.ctrl_imageb_groupBox.setObjectName(_fromUtf8("ctrl_imageb_groupBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.ctrl_imageb_groupBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.ctrl_imageb_x_groupBox = QtGui.QGroupBox(self.ctrl_imageb_groupBox)
        self.ctrl_imageb_x_groupBox.setObjectName(_fromUtf8("ctrl_imageb_x_groupBox"))
        self.gridLayout_16 = QtGui.QGridLayout(self.ctrl_imageb_x_groupBox)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.ctrl_imageb_x_kp_label = QtGui.QLabel(self.ctrl_imageb_x_groupBox)
        self.ctrl_imageb_x_kp_label.setObjectName(_fromUtf8("ctrl_imageb_x_kp_label"))
        self.gridLayout_16.addWidget(self.ctrl_imageb_x_kp_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_imageb_x_kp_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_imageb_x_groupBox)
        self.ctrl_imageb_x_kp_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_imageb_x_kp_doubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.ctrl_imageb_x_kp_doubleSpinBox.setDecimals(4)
        self.ctrl_imageb_x_kp_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_imageb_x_kp_doubleSpinBox.setObjectName(_fromUtf8("ctrl_imageb_x_kp_doubleSpinBox"))
        self.gridLayout_16.addWidget(self.ctrl_imageb_x_kp_doubleSpinBox, 0, 1, 1, 1)
        self.ctrl_imageb_x_ki_label = QtGui.QLabel(self.ctrl_imageb_x_groupBox)
        self.ctrl_imageb_x_ki_label.setObjectName(_fromUtf8("ctrl_imageb_x_ki_label"))
        self.gridLayout_16.addWidget(self.ctrl_imageb_x_ki_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_imageb_x_ki_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_imageb_x_groupBox)
        self.ctrl_imageb_x_ki_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_imageb_x_ki_doubleSpinBox.setDecimals(4)
        self.ctrl_imageb_x_ki_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_imageb_x_ki_doubleSpinBox.setObjectName(_fromUtf8("ctrl_imageb_x_ki_doubleSpinBox"))
        self.gridLayout_16.addWidget(self.ctrl_imageb_x_ki_doubleSpinBox, 1, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.ctrl_imageb_x_groupBox)
        self.ctrl_imageb_y_groupBox = QtGui.QGroupBox(self.ctrl_imageb_groupBox)
        self.ctrl_imageb_y_groupBox.setObjectName(_fromUtf8("ctrl_imageb_y_groupBox"))
        self.gridLayout_15 = QtGui.QGridLayout(self.ctrl_imageb_y_groupBox)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.ctrl_imageb_y_kp_label = QtGui.QLabel(self.ctrl_imageb_y_groupBox)
        self.ctrl_imageb_y_kp_label.setObjectName(_fromUtf8("ctrl_imageb_y_kp_label"))
        self.gridLayout_15.addWidget(self.ctrl_imageb_y_kp_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_imageb_y_kp_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_imageb_y_groupBox)
        self.ctrl_imageb_y_kp_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_imageb_y_kp_doubleSpinBox.setDecimals(4)
        self.ctrl_imageb_y_kp_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_imageb_y_kp_doubleSpinBox.setObjectName(_fromUtf8("ctrl_imageb_y_kp_doubleSpinBox"))
        self.gridLayout_15.addWidget(self.ctrl_imageb_y_kp_doubleSpinBox, 0, 1, 1, 1)
        self.ctrl_imageb_y_ki_label = QtGui.QLabel(self.ctrl_imageb_y_groupBox)
        self.ctrl_imageb_y_ki_label.setObjectName(_fromUtf8("ctrl_imageb_y_ki_label"))
        self.gridLayout_15.addWidget(self.ctrl_imageb_y_ki_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ctrl_imageb_y_ki_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_imageb_y_groupBox)
        self.ctrl_imageb_y_ki_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_imageb_y_ki_doubleSpinBox.setDecimals(4)
        self.ctrl_imageb_y_ki_doubleSpinBox.setSingleStep(0.0001)
        self.ctrl_imageb_y_ki_doubleSpinBox.setObjectName(_fromUtf8("ctrl_imageb_y_ki_doubleSpinBox"))
        self.gridLayout_15.addWidget(self.ctrl_imageb_y_ki_doubleSpinBox, 1, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.ctrl_imageb_y_groupBox)
        self.gridLayout_12.addWidget(self.ctrl_imageb_groupBox, 0, 1, 1, 1)
        self.ctrl_gp_groupBox = QtGui.QGroupBox(self.ctrl)
        self.ctrl_gp_groupBox.setMaximumSize(QtCore.QSize(16777215, 91))
        self.ctrl_gp_groupBox.setTitle(_fromUtf8(""))
        self.ctrl_gp_groupBox.setObjectName(_fromUtf8("ctrl_gp_groupBox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.ctrl_gp_groupBox)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.ctrl_gp_frq_label = QtGui.QLabel(self.ctrl_gp_groupBox)
        self.ctrl_gp_frq_label.setMaximumSize(QtCore.QSize(16777215, 21))
        self.ctrl_gp_frq_label.setObjectName(_fromUtf8("ctrl_gp_frq_label"))
        self.gridLayout_11.addWidget(self.ctrl_gp_frq_label, 0, 0, 1, 1)
        self.ctrl_gp_sigtrsh_label = QtGui.QLabel(self.ctrl_gp_groupBox)
        self.ctrl_gp_sigtrsh_label.setMaximumSize(QtCore.QSize(16777215, 21))
        self.ctrl_gp_sigtrsh_label.setObjectName(_fromUtf8("ctrl_gp_sigtrsh_label"))
        self.gridLayout_11.addWidget(self.ctrl_gp_sigtrsh_label, 0, 1, 1, 1)
        self.ctrl_gp_frq_spinBox = QtGui.QSpinBox(self.ctrl_gp_groupBox)
        self.ctrl_gp_frq_spinBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ctrl_gp_frq_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_gp_frq_spinBox.setMinimum(1)
        self.ctrl_gp_frq_spinBox.setMaximum(100)
        self.ctrl_gp_frq_spinBox.setProperty("value", 30)
        self.ctrl_gp_frq_spinBox.setObjectName(_fromUtf8("ctrl_gp_frq_spinBox"))
        self.gridLayout_11.addWidget(self.ctrl_gp_frq_spinBox, 1, 0, 1, 1)
        self.ctrl_gp_sigtrsh_doubleSpinBox = QtGui.QDoubleSpinBox(self.ctrl_gp_groupBox)
        self.ctrl_gp_sigtrsh_doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ctrl_gp_sigtrsh_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_gp_sigtrsh_doubleSpinBox.setSingleStep(0.01)
        self.ctrl_gp_sigtrsh_doubleSpinBox.setObjectName(_fromUtf8("ctrl_gp_sigtrsh_doubleSpinBox"))
        self.gridLayout_11.addWidget(self.ctrl_gp_sigtrsh_doubleSpinBox, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.ctrl_gp_groupBox, 1, 0, 1, 2)
        self.tabWidget.addTab(self.ctrl, _fromUtf8(""))
        self.mtr = QtGui.QWidget()
        self.mtr.setObjectName(_fromUtf8("mtr"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.mtr)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mtr_az_groupBox = QtGui.QGroupBox(self.mtr)
        self.mtr_az_groupBox.setObjectName(_fromUtf8("mtr_az_groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.mtr_az_groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.mtr_az_stp_radioButton = QtGui.QRadioButton(self.mtr_az_groupBox)
        self.mtr_az_stp_radioButton.setChecked(True)
        self.mtr_az_stp_radioButton.setObjectName(_fromUtf8("mtr_az_stp_radioButton"))
        self.verticalLayout_7.addWidget(self.mtr_az_stp_radioButton)
        self.mtr_az_stp_groupBox = QtGui.QGroupBox(self.mtr_az_groupBox)
        self.mtr_az_stp_groupBox.setTitle(_fromUtf8(""))
        self.mtr_az_stp_groupBox.setFlat(True)
        self.mtr_az_stp_groupBox.setObjectName(_fromUtf8("mtr_az_stp_groupBox"))
        self.gridLayout_17 = QtGui.QGridLayout(self.mtr_az_stp_groupBox)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.mtr_az_stp_stpval_label = QtGui.QLabel(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_stpval_label.setObjectName(_fromUtf8("mtr_az_stp_stpval_label"))
        self.gridLayout_17.addWidget(self.mtr_az_stp_stpval_label, 0, 0, 1, 1)
        self.mtr_az_stp_stpval_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_stpval_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_stp_stpval_doubleSpinBox.setObjectName(_fromUtf8("mtr_az_stp_stpval_doubleSpinBox"))
        self.gridLayout_17.addWidget(self.mtr_az_stp_stpval_doubleSpinBox, 1, 0, 1, 1)
        self.mtr_az_stp_micros_checkBox = QtGui.QCheckBox(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_micros_checkBox.setObjectName(_fromUtf8("mtr_az_stp_micros_checkBox"))
        self.gridLayout_17.addWidget(self.mtr_az_stp_micros_checkBox, 2, 0, 1, 1)
        self.mtr_az_stp_micros_fontComboBox = QtGui.QFontComboBox(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_micros_fontComboBox.setObjectName(_fromUtf8("mtr_az_stp_micros_fontComboBox"))
        self.gridLayout_17.addWidget(self.mtr_az_stp_micros_fontComboBox, 3, 0, 1, 1)
        self.mtr_az_stp_hspos_label = QtGui.QLabel(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_hspos_label.setObjectName(_fromUtf8("mtr_az_stp_hspos_label"))
        self.gridLayout_17.addWidget(self.mtr_az_stp_hspos_label, 4, 0, 1, 1)
        self.mtr_az_stp_hspos_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_hspos_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_stp_hspos_doubleSpinBox.setObjectName(_fromUtf8("mtr_az_stp_hspos_doubleSpinBox"))
        self.gridLayout_17.addWidget(self.mtr_az_stp_hspos_doubleSpinBox, 5, 0, 1, 1)
        self.mtr_az_stp_gr_groupBox = QtGui.QGroupBox(self.mtr_az_stp_groupBox)
        self.mtr_az_stp_gr_groupBox.setObjectName(_fromUtf8("mtr_az_stp_gr_groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.mtr_az_stp_gr_groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mtr_az_stp_gr_in_spinBox = QtGui.QSpinBox(self.mtr_az_stp_gr_groupBox)
        self.mtr_az_stp_gr_in_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_stp_gr_in_spinBox.setObjectName(_fromUtf8("mtr_az_stp_gr_in_spinBox"))
        self.horizontalLayout_4.addWidget(self.mtr_az_stp_gr_in_spinBox)
        self.mtr_az_stp_gr_out_spinBox = QtGui.QSpinBox(self.mtr_az_stp_gr_groupBox)
        self.mtr_az_stp_gr_out_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_stp_gr_out_spinBox.setObjectName(_fromUtf8("mtr_az_stp_gr_out_spinBox"))
        self.horizontalLayout_4.addWidget(self.mtr_az_stp_gr_out_spinBox)
        self.gridLayout_17.addWidget(self.mtr_az_stp_gr_groupBox, 6, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.mtr_az_stp_groupBox)
        self.mtr_az_dc_radioButton = QtGui.QRadioButton(self.mtr_az_groupBox)
        self.mtr_az_dc_radioButton.setObjectName(_fromUtf8("mtr_az_dc_radioButton"))
        self.verticalLayout_7.addWidget(self.mtr_az_dc_radioButton)
        self.mtr_az_dc_groupBox = QtGui.QGroupBox(self.mtr_az_groupBox)
        self.mtr_az_dc_groupBox.setTitle(_fromUtf8(""))
        self.mtr_az_dc_groupBox.setFlat(True)
        self.mtr_az_dc_groupBox.setObjectName(_fromUtf8("mtr_az_dc_groupBox"))
        self.gridLayout_19 = QtGui.QGridLayout(self.mtr_az_dc_groupBox)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.mtr_az_dc_epval_label = QtGui.QLabel(self.mtr_az_dc_groupBox)
        self.mtr_az_dc_epval_label.setObjectName(_fromUtf8("mtr_az_dc_epval_label"))
        self.gridLayout_19.addWidget(self.mtr_az_dc_epval_label, 0, 0, 1, 1)
        self.mtr_az_dc_epval_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_az_dc_groupBox)
        self.mtr_az_dc_epval_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_dc_epval_doubleSpinBox.setObjectName(_fromUtf8("mtr_az_dc_epval_doubleSpinBox"))
        self.gridLayout_19.addWidget(self.mtr_az_dc_epval_doubleSpinBox, 1, 0, 1, 1)
        self.mtr_az_dc_hspos_label = QtGui.QLabel(self.mtr_az_dc_groupBox)
        self.mtr_az_dc_hspos_label.setObjectName(_fromUtf8("mtr_az_dc_hspos_label"))
        self.gridLayout_19.addWidget(self.mtr_az_dc_hspos_label, 2, 0, 1, 1)
        self.mtr_az_dc_hspos_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_az_dc_groupBox)
        self.mtr_az_dc_hspos_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_dc_hspos_doubleSpinBox.setObjectName(_fromUtf8("mtr_az_dc_hspos_doubleSpinBox"))
        self.gridLayout_19.addWidget(self.mtr_az_dc_hspos_doubleSpinBox, 3, 0, 1, 1)
        self.mtr_az_dc_gr_groupBox = QtGui.QGroupBox(self.mtr_az_dc_groupBox)
        self.mtr_az_dc_gr_groupBox.setObjectName(_fromUtf8("mtr_az_dc_gr_groupBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.mtr_az_dc_gr_groupBox)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mtr_az_dc_gr_in_spinBox = QtGui.QSpinBox(self.mtr_az_dc_gr_groupBox)
        self.mtr_az_dc_gr_in_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_dc_gr_in_spinBox.setObjectName(_fromUtf8("mtr_az_dc_gr_in_spinBox"))
        self.horizontalLayout_6.addWidget(self.mtr_az_dc_gr_in_spinBox)
        self.mtr_az_dc_gr_out_spinBox = QtGui.QSpinBox(self.mtr_az_dc_gr_groupBox)
        self.mtr_az_dc_gr_out_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_az_dc_gr_out_spinBox.setObjectName(_fromUtf8("mtr_az_dc_gr_out_spinBox"))
        self.horizontalLayout_6.addWidget(self.mtr_az_dc_gr_out_spinBox)
        self.gridLayout_19.addWidget(self.mtr_az_dc_gr_groupBox, 4, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.mtr_az_dc_groupBox)
        self.horizontalLayout_8.addWidget(self.mtr_az_groupBox)
        self.mtr_el_groupBox = QtGui.QGroupBox(self.mtr)
        self.mtr_el_groupBox.setObjectName(_fromUtf8("mtr_el_groupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.mtr_el_groupBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.mtr_el_stp_radioButton = QtGui.QRadioButton(self.mtr_el_groupBox)
        self.mtr_el_stp_radioButton.setChecked(True)
        self.mtr_el_stp_radioButton.setObjectName(_fromUtf8("mtr_el_stp_radioButton"))
        self.verticalLayout_8.addWidget(self.mtr_el_stp_radioButton)
        self.mtr_el_stp_groupBox = QtGui.QGroupBox(self.mtr_el_groupBox)
        self.mtr_el_stp_groupBox.setTitle(_fromUtf8(""))
        self.mtr_el_stp_groupBox.setFlat(True)
        self.mtr_el_stp_groupBox.setObjectName(_fromUtf8("mtr_el_stp_groupBox"))
        self.gridLayout_18 = QtGui.QGridLayout(self.mtr_el_stp_groupBox)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.mtr_el_stp_stpval_label = QtGui.QLabel(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_stpval_label.setObjectName(_fromUtf8("mtr_el_stp_stpval_label"))
        self.gridLayout_18.addWidget(self.mtr_el_stp_stpval_label, 0, 0, 1, 1)
        self.mtr_el_stp_stpval_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_stpval_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_el_stp_stpval_doubleSpinBox.setObjectName(_fromUtf8("mtr_el_stp_stpval_doubleSpinBox"))
        self.gridLayout_18.addWidget(self.mtr_el_stp_stpval_doubleSpinBox, 1, 0, 1, 1)
        self.mtr_el_stp_micros_checkBox = QtGui.QCheckBox(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_micros_checkBox.setObjectName(_fromUtf8("mtr_el_stp_micros_checkBox"))
        self.gridLayout_18.addWidget(self.mtr_el_stp_micros_checkBox, 2, 0, 1, 1)
        self.mtr_el_stp_micros_fontComboBox = QtGui.QFontComboBox(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_micros_fontComboBox.setObjectName(_fromUtf8("mtr_el_stp_micros_fontComboBox"))
        self.gridLayout_18.addWidget(self.mtr_el_stp_micros_fontComboBox, 3, 0, 1, 1)
        self.mtr_el_stp_hspos_label = QtGui.QLabel(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_hspos_label.setObjectName(_fromUtf8("mtr_el_stp_hspos_label"))
        self.gridLayout_18.addWidget(self.mtr_el_stp_hspos_label, 4, 0, 1, 1)
        self.mtr_el_stp_hspos_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_hspos_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_el_stp_hspos_doubleSpinBox.setObjectName(_fromUtf8("mtr_el_stp_hspos_doubleSpinBox"))
        self.gridLayout_18.addWidget(self.mtr_el_stp_hspos_doubleSpinBox, 5, 0, 1, 1)
        self.mtr_el_stp_gr_groupBox = QtGui.QGroupBox(self.mtr_el_stp_groupBox)
        self.mtr_el_stp_gr_groupBox.setObjectName(_fromUtf8("mtr_el_stp_gr_groupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.mtr_el_stp_gr_groupBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mtr_el_stp_gr_in_pinBox = QtGui.QSpinBox(self.mtr_el_stp_gr_groupBox)
        self.mtr_el_stp_gr_in_pinBox.setObjectName(_fromUtf8("mtr_el_stp_gr_in_pinBox"))
        self.horizontalLayout_5.addWidget(self.mtr_el_stp_gr_in_pinBox)
        self.mtr_el_stp_gr_out_spinBox = QtGui.QSpinBox(self.mtr_el_stp_gr_groupBox)
        self.mtr_el_stp_gr_out_spinBox.setObjectName(_fromUtf8("mtr_el_stp_gr_out_spinBox"))
        self.horizontalLayout_5.addWidget(self.mtr_el_stp_gr_out_spinBox)
        self.gridLayout_18.addWidget(self.mtr_el_stp_gr_groupBox, 6, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.mtr_el_stp_groupBox)
        self.mtr_el_dc_radioButton = QtGui.QRadioButton(self.mtr_el_groupBox)
        self.mtr_el_dc_radioButton.setObjectName(_fromUtf8("mtr_el_dc_radioButton"))
        self.verticalLayout_8.addWidget(self.mtr_el_dc_radioButton)
        self.mtr_el_dc_groupBox = QtGui.QGroupBox(self.mtr_el_groupBox)
        self.mtr_el_dc_groupBox.setTitle(_fromUtf8(""))
        self.mtr_el_dc_groupBox.setFlat(True)
        self.mtr_el_dc_groupBox.setObjectName(_fromUtf8("mtr_el_dc_groupBox"))
        self.gridLayout_20 = QtGui.QGridLayout(self.mtr_el_dc_groupBox)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.mtr_el_dc_epval_label = QtGui.QLabel(self.mtr_el_dc_groupBox)
        self.mtr_el_dc_epval_label.setObjectName(_fromUtf8("mtr_el_dc_epval_label"))
        self.gridLayout_20.addWidget(self.mtr_el_dc_epval_label, 0, 0, 1, 1)
        self.mtr_el_dc_epval_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_el_dc_groupBox)
        self.mtr_el_dc_epval_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_el_dc_epval_doubleSpinBox.setObjectName(_fromUtf8("mtr_el_dc_epval_doubleSpinBox"))
        self.gridLayout_20.addWidget(self.mtr_el_dc_epval_doubleSpinBox, 1, 0, 1, 1)
        self.mtr_el_dc_hspos_label = QtGui.QLabel(self.mtr_el_dc_groupBox)
        self.mtr_el_dc_hspos_label.setObjectName(_fromUtf8("mtr_el_dc_hspos_label"))
        self.gridLayout_20.addWidget(self.mtr_el_dc_hspos_label, 2, 0, 1, 1)
        self.mtr_el_dc_hspos_doubleSpinBox = QtGui.QDoubleSpinBox(self.mtr_el_dc_groupBox)
        self.mtr_el_dc_hspos_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_el_dc_hspos_doubleSpinBox.setObjectName(_fromUtf8("mtr_el_dc_hspos_doubleSpinBox"))
        self.gridLayout_20.addWidget(self.mtr_el_dc_hspos_doubleSpinBox, 3, 0, 1, 1)
        self.mtr_el_dc_gr_groupBox = QtGui.QGroupBox(self.mtr_el_dc_groupBox)
        self.mtr_el_dc_gr_groupBox.setObjectName(_fromUtf8("mtr_el_dc_gr_groupBox"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.mtr_el_dc_gr_groupBox)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mtr_el_dc_gr_in_pinBox = QtGui.QSpinBox(self.mtr_el_dc_gr_groupBox)
        self.mtr_el_dc_gr_in_pinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_el_dc_gr_in_pinBox.setObjectName(_fromUtf8("mtr_el_dc_gr_in_pinBox"))
        self.horizontalLayout_7.addWidget(self.mtr_el_dc_gr_in_pinBox)
        self.mtr_el_dc_gr_out_spinBox = QtGui.QSpinBox(self.mtr_el_dc_gr_groupBox)
        self.mtr_el_dc_gr_out_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mtr_el_dc_gr_out_spinBox.setObjectName(_fromUtf8("mtr_el_dc_gr_out_spinBox"))
        self.horizontalLayout_7.addWidget(self.mtr_el_dc_gr_out_spinBox)
        self.gridLayout_20.addWidget(self.mtr_el_dc_gr_groupBox, 4, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.mtr_el_dc_groupBox)
        self.horizontalLayout_8.addWidget(self.mtr_el_groupBox)
        self.tabWidget.addTab(self.mtr, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionRestore_Default = QtGui.QAction(MainWindow)
        self.actionRestore_Default.setObjectName(_fromUtf8("actionRestore_Default"))
        self.actionRestart = QtGui.QAction(MainWindow)
        self.actionRestart.setObjectName(_fromUtf8("actionRestart"))
        self.actionSutdown = QtGui.QAction(MainWindow)
        self.actionSutdown.setObjectName(_fromUtf8("actionSutdown"))
        self.actionExit_to_Terminal = QtGui.QAction(MainWindow)
        self.actionExit_to_Terminal.setObjectName(_fromUtf8("actionExit_to_Terminal"))
        self.menuAction.addAction(self.actionLoad)
        self.menuAction.addAction(self.actionSave)
        self.menuAction.addAction(self.actionRestore_Default)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionRestart)
        self.menuAction.addAction(self.actionSutdown)
        self.menuAction.addAction(self.actionExit_to_Terminal)
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.trkr_src_autofl_radioButton_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.trkr_loc_groupBox.setDisabled)
        QtCore.QObject.connect(self.mtr_el_dc_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mtr_el_dc_groupBox.setEnabled)
        QtCore.QObject.connect(self.trkr_typ_col_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.trkr_typ_cpfh_radioButtongroupBox.setDisabled)
        QtCore.QObject.connect(self.mtr_el_stp_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mtr_el_stp_groupBox.setEnabled)
        QtCore.QObject.connect(self.mtr_az_stp_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mtr_az_stp_groupBox.setEnabled)
        QtCore.QObject.connect(self.mtr_az_dc_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mtr_az_dc_groupBox.setEnabled)
        QtCore.QObject.connect(self.gen_man_auto_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.gen_man_btn_rst_pushButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Solar Tracker User Interface", None))
        self.gen_impro_groupBox.setTitle(_translate("MainWindow", "Image Processing", None))
        self.gen_impro_imsrc_label.setText(_translate("MainWindow", "Image Source", None))
        self.gen_impro_reso_label.setText(_translate("MainWindow", "Resolution", None))
        self.gen_impro_opker_label.setText(_translate("MainWindow", "Opening Kernel Size", None))
        self.gen_impro_blrker_label.setText(_translate("MainWindow", "Blur Kernel Size", None))
        self.gen_man_btn_groupBox.setTitle(_translate("MainWindow", "Manual Control", None))
        self.gen_man_btn_up_pushButton.setText(_translate("MainWindow", "up", None))
        self.gen_man_btn_up_pushButton.setShortcut(_translate("MainWindow", "Up", None))
        self.gen_man_man_radioButton.setText(_translate("MainWindow", "Manual (Motors)", None))
        self.gen_man_btn_lft_pushButton.setText(_translate("MainWindow", "left", None))
        self.gen_man_btn_lft_pushButton.setShortcut(_translate("MainWindow", "Left", None))
        self.gen_man_btn_dwn_pushButton.setText(_translate("MainWindow", "down", None))
        self.gen_man_btn_dwn_pushButton.setShortcut(_translate("MainWindow", "Down", None))
        self.gen_man_btn_rt_pushButton.setText(_translate("MainWindow", "right", None))
        self.gen_man_btn_rt_pushButton.setShortcut(_translate("MainWindow", "Right", None))
        self.gen_man_auto_radioButton.setText(_translate("MainWindow", "Auto (Target Set Point)", None))
        self.gen_man_btn_rst_pushButton.setText(_translate("MainWindow", "Reset", None))
        self.gen_daily_groupBox.setTitle(_translate("MainWindow", "Daily Schedule (Global Time)", None))
        self.gen_daily_strt_groupBox.setTitle(_translate("MainWindow", "Start", None))
        self.gen_daily_strt_timeEdit.setDisplayFormat(_translate("MainWindow", "H:mm", None))
        self.gen_daily_stp_groupBox.setTitle(_translate("MainWindow", "Stop", None))
        self.gen_daily_stp_timeEdit.setDisplayFormat(_translate("MainWindow", "H:mm", None))
        self.gen_daily_stp_rts_checkBox.setText(_translate("MainWindow", "Return To Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gen), _translate("MainWindow", "General", None))
        self.trkr_src_groupBox.setTitle(_translate("MainWindow", "source", None))
        self.trkr_src_usdef_radioButton.setText(_translate("MainWindow", "Uesr Defined", None))
        self.trkr_src_autofl_radioButton_2.setText(_translate("MainWindow", "AutoFill", None))
        self.trkr_loc_groupBox.setTitle(_translate("MainWindow", "Location", None))
        self.trkr_loc_lat_groupBox.setTitle(_translate("MainWindow", "Lattitude", None))
        self.trkr_loc_lat_deg_label.setText(_translate("MainWindow", "Degrees", None))
        self.trkr_loc_lat_min_label.setText(_translate("MainWindow", "Minutes", None))
        self.trkr_loc_lat_sec_label.setText(_translate("MainWindow", "Seconds", None))
        self.trkr_loc_lon_groupBox.setTitle(_translate("MainWindow", "Longitude", None))
        self.trkr_loc_lon_deg_label.setText(_translate("MainWindow", "Degrees", None))
        self.trkr_loc_lon_min_label.setText(_translate("MainWindow", "Minutes", None))
        self.trkr_loc_lon_sec_label.setText(_translate("MainWindow", "Seconds", None))
        self.trkr_loc_alt_groupBox.setTitle(_translate("MainWindow", "Alttitude [m]", None))
        self.trkr_loc_td_groupBox.setTitle(_translate("MainWindow", "Time and Date", None))
        self.trkr_loc_td_time_label.setText(_translate("MainWindow", "Global Time (UTC)", None))
        self.trkr_loc_td_date_label.setText(_translate("MainWindow", "Date", None))
        self.trkr_loc_td_time_timeEdit.setDisplayFormat(_translate("MainWindow", "H:mm:ss", None))
        self.trkr_typ_groupBox.setTitle(_translate("MainWindow", "Type", None))
        self.trkr_typ_col_radioButton.setText(_translate("MainWindow", "Collector", None))
        self.trkr_typ_cpfh_radioButtongroupBox.setTitle(_translate("MainWindow", "Collector Position From Heliostat", None))
        self.trkr_typ_cpfh_az_groupBox.setTitle(_translate("MainWindow", "Azimuth", None))
        self.trkr_typ_cpfh_el_groupBox.setTitle(_translate("MainWindow", "Elevation", None))
        self.trkr_typ_heli_radioButton.setText(_translate("MainWindow", "Helliostat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trkr), _translate("MainWindow", "Tracker", None))
        self.ctrl_timeb_groupBox.setTitle(_translate("MainWindow", "Time Based", None))
        self.ctrl_timeb_az_groupBox.setTitle(_translate("MainWindow", "Azimuth", None))
        self.ctrl_timeb_az_kp_label.setText(_translate("MainWindow", "Kp", None))
        self.ctrl_timeb_az_ki_label.setText(_translate("MainWindow", "Ki", None))
        self.ctrl_timeb_el_groupBox.setTitle(_translate("MainWindow", "Elevation", None))
        self.ctrl_timeb_el_kp_label.setText(_translate("MainWindow", "Kp", None))
        self.ctrl_timeb_el_ki_label.setText(_translate("MainWindow", "Ki", None))
        self.ctrl_imageb_groupBox.setTitle(_translate("MainWindow", "Image Based", None))
        self.ctrl_imageb_x_groupBox.setTitle(_translate("MainWindow", "X", None))
        self.ctrl_imageb_x_kp_label.setText(_translate("MainWindow", "Kp", None))
        self.ctrl_imageb_x_ki_label.setText(_translate("MainWindow", "Ki", None))
        self.ctrl_imageb_y_groupBox.setTitle(_translate("MainWindow", "Y", None))
        self.ctrl_imageb_y_kp_label.setText(_translate("MainWindow", "Kp", None))
        self.ctrl_imageb_y_ki_label.setText(_translate("MainWindow", "Ki", None))
        self.ctrl_gp_frq_label.setText(_translate("MainWindow", "Frecuency [Hz]", None))
        self.ctrl_gp_sigtrsh_label.setText(_translate("MainWindow", "Azimuth Signal Transition Threshold", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ctrl), _translate("MainWindow", "Controller", None))
        self.mtr_az_groupBox.setTitle(_translate("MainWindow", "Azimuth", None))
        self.mtr_az_stp_radioButton.setText(_translate("MainWindow", "Stepper Motor", None))
        self.mtr_az_stp_stpval_label.setText(_translate("MainWindow", "Step Value [deg]", None))
        self.mtr_az_stp_micros_checkBox.setText(_translate("MainWindow", "Micro Step", None))
        self.mtr_az_stp_hspos_label.setText(_translate("MainWindow", "Home Switch Position [deg]", None))
        self.mtr_az_stp_gr_groupBox.setTitle(_translate("MainWindow", "Gear Ratio", None))
        self.mtr_az_dc_radioButton.setText(_translate("MainWindow", "DC Motor", None))
        self.mtr_az_dc_epval_label.setText(_translate("MainWindow", "Encoder Pulse Value [deg]", None))
        self.mtr_az_dc_hspos_label.setText(_translate("MainWindow", "Home Switch Position [deg]", None))
        self.mtr_az_dc_gr_groupBox.setTitle(_translate("MainWindow", "Gear Ratio", None))
        self.mtr_el_groupBox.setTitle(_translate("MainWindow", "Elevation", None))
        self.mtr_el_stp_radioButton.setText(_translate("MainWindow", "Stepper Motor", None))
        self.mtr_el_stp_stpval_label.setText(_translate("MainWindow", "Step Value [deg]", None))
        self.mtr_el_stp_micros_checkBox.setText(_translate("MainWindow", "Micro Step", None))
        self.mtr_el_stp_hspos_label.setText(_translate("MainWindow", "Home Switch Position [deg]", None))
        self.mtr_el_stp_gr_groupBox.setTitle(_translate("MainWindow", "Gear Ratio", None))
        self.mtr_el_dc_radioButton.setText(_translate("MainWindow", "DC Motor", None))
        self.mtr_el_dc_epval_label.setText(_translate("MainWindow", "Encoder Pulse Value [deg]", None))
        self.mtr_el_dc_hspos_label.setText(_translate("MainWindow", "Home Switch Position [deg]", None))
        self.mtr_el_dc_gr_groupBox.setTitle(_translate("MainWindow", "Gear Ratio", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mtr), _translate("MainWindow", "Motors", None))
        self.menuAction.setTitle(_translate("MainWindow", "Action", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionRestore_Default.setText(_translate("MainWindow", "Restore Default", None))
        self.actionRestart.setText(_translate("MainWindow", "Restart", None))
        self.actionSutdown.setText(_translate("MainWindow", "Sutdown", None))
        self.actionExit_to_Terminal.setText(_translate("MainWindow", "Exit to Terminal", None))


if __name__ == "__main__":
    import sys    
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

